export const FETCH_BOOK_LIST = "FETCH_BOOK_LIST"
export const FETCH_BOOK_LIST_RESPONSE = "FETCH_BOOK_LIST_RESPONSE"
export const FETCH_BOOK_LIST_ERROR = "FETCH_BOOK_LIST_ERROR"

export const FETCH_BOOK_COVER_IMG = "FETCH_BOOK_COVER_IMG"
export const FETCH_BOOK_COVER_IMG_RESPONSE = "FETCH_BOOK_COVER_IMG_RESPONSE"
export const FETCH_BOOK_COVER_IMG_ERROR = "FETCH_BOOK_COVER_IMG_ERROR"

